---
# Source: flask-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  labels:
    app: flask-app

spec:
  type: NodePort
  selector:
    app: flask-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
---
# Source: flask-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask-app
          image: mohammedkhalil7/flask-app:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          env:
            - name: ENVIRONMENT
              value: production

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu:  500m
              memory:  512Mi

          volumeMounts:
            - name: flask-storage
              mountPath: /data

      volumes:
        - name: flask-storage
          emptyDir: {}

      restartPolicy: Always
