service:
  type: NodePort
  targetport: 8000
  port: 80 
  nodePort: 30080

deployment:
  replicas: 3
  imagetag: "1.0.0"
  imagerepo : mohammedkhalil7/flask-app    # from the image i built 
  containerport: 3000


env: 
  value: "production"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

